ADColony 4.1 SDK support
notmedia/cordova-plugin-adcolony pull request #3
Opened 2019-09-27 12:58 UTC by ferdil

I've updated the code for both iOS and Android to support the newer Cordova and AdColony SDKs

2019-10-09 06:52 UTC, notmedia commented
@ferdil Cool, can you resolve conflicts?

2019-10-09 15:15 UTC, ferdil commented
Hi - don't have write access to your repo. Can you give me access ?

2019-10-09 15:42 UTC, notmedia commented
Done, check it out

2019-10-09 15:42 UTC, notmedia approved these changes

2019-10-10 18:31 UTC, notmedia commented
You should sync your fork with this repo and resolve conflicts - https://help.github.com/en/articles/syncing-a-fork

After that, this PR will automatically update.

2019-10-11 13:47 UTC, ferdil commented
Looks like I don't have write access to the repo

2019-10-14 22:50 UTC, notmedia requested changes

2019-10-14 22:50 UTC, notmedia commented on src/android/com/adcolony/plugin/AdColonyPlugin.java
> +>>>>>>> upstream/master
conflict resolve problem here

2019-10-15 04:40 UTC, ferdil reviewed
Not sure what I need to do here - I can't make changes and I can't approve it ?

2019-10-15 04:47 UTC, ferdil reviewed
Fixes done

2019-10-15 07:07 UTC, merged

2019-10-15 07:08 UTC, notmedia commented
Thank you